{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lineying.sdk",
    "module": "numberkeyboard",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "numberkeyboard-1.0.0.aar",
          "url": "numberkeyboard-1.0.0.aar",
          "size": 416225,
          "sha512": "f3b94ffbe251525326831785955a7d6c4bdc5773d2ce7f278e87c3e3fb9a939411d581c512f25bcd10ffea656f7ba93c0f45d3f130bfed3f4e5a7d1edd2937e0",
          "sha256": "6576aafa123f2b145c730209a54339e438b3446568916cdaa36416e939f798c6",
          "sha1": "54665031f3713fdad263a26b7d443cf87ef39200",
          "md5": "d91ee77c383536b6c8699b05cac0d249"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.20"
          }
        }
      ],
      "files": [
        {
          "name": "numberkeyboard-1.0.0.aar",
          "url": "numberkeyboard-1.0.0.aar",
          "size": 416225,
          "sha512": "f3b94ffbe251525326831785955a7d6c4bdc5773d2ce7f278e87c3e3fb9a939411d581c512f25bcd10ffea656f7ba93c0f45d3f130bfed3f4e5a7d1edd2937e0",
          "sha256": "6576aafa123f2b145c730209a54339e438b3446568916cdaa36416e939f798c6",
          "sha1": "54665031f3713fdad263a26b7d443cf87ef39200",
          "md5": "d91ee77c383536b6c8699b05cac0d249"
        }
      ]
    }
  ]
}
