{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lineying.sdk",
    "module": "admanager",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "admanager-1.0.1.aar",
          "url": "admanager-1.0.1.aar",
          "size": 91136,
          "sha512": "a4a07eb136009d33690fa00cab97cb378b617d64ce15adee84c7208acb8b8764ed1a3a8cdec049c7da25f7362540043a3a6338f526fd852ef7dd4d1093be07c1",
          "sha256": "f0dba10e562a3f6d4e6dd0614543c754108fda81595a643ceaddb411a2b80ebf",
          "sha1": "199697ed8c8b96833497b8d3751852412f2a6444",
          "md5": "6207e058b79229cf5a7157d3163e39c4"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.github.bumptech.glide",
          "module": "glide",
          "version": {
            "requires": "4.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "admanager-1.0.1.aar",
          "url": "admanager-1.0.1.aar",
          "size": 91136,
          "sha512": "a4a07eb136009d33690fa00cab97cb378b617d64ce15adee84c7208acb8b8764ed1a3a8cdec049c7da25f7362540043a3a6338f526fd852ef7dd4d1093be07c1",
          "sha256": "f0dba10e562a3f6d4e6dd0614543c754108fda81595a643ceaddb411a2b80ebf",
          "sha1": "199697ed8c8b96833497b8d3751852412f2a6444",
          "md5": "6207e058b79229cf5a7157d3163e39c4"
        }
      ]
    }
  ]
}
